# Generated by Django 3.2.7 on 2021-09-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='users',
        ),
    ]
