# Generated by Django 3.2.7 on 2021-09-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_rename_users_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='users',
        ),
    ]
